import os

BACKGROUND_IMAGE_FILENAME = "card_bg_09.png"
BACKGROUND_IMAGE_PATH = os.path.join("assets", BACKGROUND_IMAGE_FILENAME)
BACKGROUND_IMAGE_PLACEHOLDER = f"../assets/{BACKGROUND_IMAGE_FILENAME}"